### ISSUE TITLE
Loading a savegame throws "__StrictEngagements__/control.lua:39: attempt to call global 'newPlayerInit' (a nil value)"

### ISSUE THREAD

**Issue by mrbaguettefr** [Nexela/NoTurretCreep#1]
I loaded a savegame who did not have StrickEngagements activated.
It throws this error:
__StrictEngagements__/control.lua:39: attempt to call global 'newPlayerInit' (a nil value)

It might be other mods interfering with the mod because I have a lot installed. I'm not an expert of Lua so I'm just guessing.

I've just forked the project and I will try to find out what's happening.

**Comment by Nexela** [comment]
I probably broke something. This was one of my earlier mods while learning
lua and factorio modding.  Ill open it up and take a peek in a few minutes
